.\" SPDX-License-Identifier: BSL-1.0
.\" Manpage für chr
.\" Machen Sie Pull Requests auf: https://github.com/istoph/editor oder erstellen Sie ein Issue für Fehlerkorrekturen.
.TH man 1 "28 Nov 2018" "1.0" "chr man page"
.SH NAME
chr \- chr ist ein konsolenbasierter Editor
.SH SYNOPSIS
Usage: chr [options] [[+line[,char]] file …] [/directory]
chr

Options:
  -h, --help                          Displays this help.
  -v, --version                       Displays version information.
  -l, --linenumber                    The line numbers are displayed
  -a, --append <file>                 Only with read from standard input, then
                                      append to a file
  -f, --follow                        Only with read from standard input, then
                                      follow the input stream
  -b                                  Open bigger file then 1MB
  -w                                  Wrap log lines
  --attributesfile <config>           Safe file for attributes, default
                                      ~/.cache/chr.json
  -c, --config <config>               Load customized config file. The default
                                      if it exist is ~/.config/chr
  --syntax-highlighting-theme <name>  Name of syntax-highlighting-theme, you
                                      can list installed themes with:
                                      kate-syntax-highlighter --list-themes
  --disable-syntax                    disable syntax highlighting

Arguments:
  [[+line[,char]] file …]             Optional is the line number, several
                                      files can be opened in multiple windows.
  [/directory]                        Or a directory can be specified to search
                                      in the open dialog.

.SH FILES
~/.config/chr
  Your personal chr initializations.

~/.cache/chr.json
  History über die geänderten Dateien. Hierin werden Positionen von Cursor gespeichert.

.SH SHORT CUTS
Shift + Coursor
  Markiert den Text

Ctrl + a
  Markiert den gesamten Text

Ctrl + c, Ctrl + Insert
  Kopiert den markierten Text

Ctrl + d
  Löscht die aktuelle Zeile

Ctrl + e, hoch/runter/links/rechts
  Wechselt das aktive Fenster. Mit den Pfeil Tastern gibt man den Ort des nächsten aktiven Fensters an.

Ctrl + e + Ctrl + hoch/runter/links/rechts
  Fenstergröße verändern.

Ctrl + f
  Öffnet den "Suchen"-Dialog

Ctrl + h, Shift + Backspace
  Löscht ein Wort

Ctrl + r
  Öffnet den "Ersetzen"-Dialog

Ctrl + n
  Erstellt eine neue Datei

Ctrl + q
  Programm verlassen

Ctrl + s
  Speichern oder Speichern unter...

Ctrl + v, Shift + Insert
  Einfügen an Cursorposition

Ctrl + x, Shift + Delete
  Ausschneiden des markierten Texts

Ctrl + y
  Stellt eine rückgängig gemachte Aktion wieder her.

Ctrl + z
  Macht eine Aktion rückgängig.

Ctrl + Shift + up
  Verschiebt eine Zeile nach oben

Ctrl + Shift + down
  Verschiebt eine Zeile nach unten

Ctrl + Left
  Springt ein Wort nach links

Ctrl + Shift + Left
  Markiert ein Wort nach links

Ctrl + Rechts
  Springt ein Wort nach rechts

Ctrl + Shift Right
  Markiert ein Wort nach rechts

Alt + -
  Öffnet das Fenster-Menü

Alt + Shift + hoch/runter/links/rechts
  Markiert den Text in Blöcken. Das Einfügen der Zwischenablage dupliziert den Text je Zeile. Wird eine gleich große Anzahl an Zeilen markiert wie eingefügt werden soll, werden nur diese eingefügt.

Alt + Shift + S
  Markierte Zeilen werden alphabetisch sortiert.

Alt + x
  Öffnet eine versteckte Kommandozeile. Für weitere Hilfe "help" eintippen.

Tab, Shift + Tab
  Rückt einen markierten Block um einen Tabulator ein oder entfernt diesen.

F3, Shift + F3
  Springt zum nächsten oder vorherigen Suchwort

F4
  Wechselt den Markierungsmodus, um das Markieren in Konsolen mit unterdrückter Umschalttaste zu unterstützen

F6, Shift + F6
  Wechselt das aktive Fenster, mit Shift in umgekehrter Reihenfolge.

Esc
  Schließt ein aktives Fenster, ein Menü oder beendet eine Aktion.

.SH Menu
.SH New
Prüft, ob die aktuell offene Datei gespeichert werden muss und zeigt eine leere Datei an.

.SH Open
Öffnet einen Dateidialog, um eine zu öffnende Datei auszuwählen.

.SH Save or Save as...
Speichert den aktuellen Stand der Datei. Sollte der Speicherpfad noch nicht angegeben sein, wird der "Save as..." Dialog geöffnet. Hier kann über ein Dateidialog ein Speicherort ausgewählt werden.

.SH Reload
Lädt die aktuelle Datei neu. Dabei werden alle Änderungen verworfen.

.SH Close
Schließt das aktive Fenster.

.SH Quit
Beendet den Editor. Sollte noch eine ungespeicherte Datei geöffnet sein, wird zuvor der Speichern-Dialog aufgerufen.

.SH Cut, Copy, Paste, Select all
Mit den Pfeiltasten und dem gleichzeitigen gedrückt halten der Umschalttaste kann Text markiert werden. Der gesamte Text kann mit (Select all) markiert werden.
Dieser markierte Text kann dann mittels (Copy) kopiert oder mit (Cut) ausgeschnitten werden. Mit (Paste) kann dieser Text an der aktuellen Cursorposition wieder eingefügt werden. Das mehrfache Kopieren von Text führt zum Verlust der Zeichenablage (copy buffer).

Es ist je nach Terminal zwischen den 3 Copy Buffern zu unterscheiden. 1. Dem in den Editor integrierten Copy Buffer. 2. Dem Maus Copy Buffer 3. Dem Desktop Copy Buffer.

.SH Undo und Redo
Mit Undo oder STRG + z können Eingaben wieder rückgängig gemacht werden. Mit Redo oder STRG + y können rückgängig gemachte Änderungen wiederhergestellt werden.

.SH Search
Mit Search oder STRG + f wird der Suchen-Dialog geöffnet. Unter "Find" gibt man ein Suchwort ein. Über die Optionen kann man die Suche verfeinern. Im Hintergrund wird dann eine Livesuche durchgeführt. Mit F3 wird das nächste bzw. mit Umschalt + F3 das vorherige gefundene Element markiert.

.SH Search Next
Mit F3 wird das nächste Suchergebnis markiert.

.SH Search Previous
Mit Shift + F3 wird das vorherige Suchergebnis markiert.

.SH Cut Line
Die gesamte Zeile wird ausgeschnitten.

.SH Replace
Mit Replace oder STRG + r wird der "Ersetzen"-Dialog geöffnet. Im Feld "Find" wird das Suchwort angegeben. Im Feld "Replace" wird das Wort angegeben, das eingefügt werden soll. Mit: "Next" wird das nächste Suchwort gesucht. Mit: "Replace" wird das Suchwort ersetzt. Mit: "All" werden alle Suchergebnisse ersetzt.

.SH Goto
Öffnet einen Dialog, um zu einer Zeile zu springen.

.SH Sort Selcted Lines
Sortiert markierte Zeilen in alphabetischer Reihenfolge.

.SH Tab
Öffnet den Tab-Dialog. Hier können die Einstellungen für die Einrückung vorgenommen werden. Es kann zwischen Tab (\\t) und Leerzeichen gewählt werden. Zudem kann die Anzahl der Leerzeichen festgelegt werden. Die Standardeinstellungen können auch in der ~/.config/chr Datei vorgenommen werden. Hier kann: "tabsize=8" oder "tab=false" für Leerzeichen angegeben werden.

.SH Line Number
Schaltet die Darstellung der Zeilennummern auf der rechten Seite des Editors ein. Die Standardeinstellungen können auch in der ~/.config/chr Datei vorgenommen werden. Hier kann: "linenumber=true" angegeben werden.

.SH Formatting
Im Formatting-Dialog können "Formatting Characters", "Color Tabs" und "Color Spacs at end of line"  ein und ausgestalltet werden.

"Formatting characters" kennzeichnen Leerzeichen mit einem Punkt: "·", Zeilenenden (\n) durch ein "¶" und das Ende der Datei mit: "♦". Alternativ kann diese Anzeige auch ausgeschaltet werden.

Mit "Color Tabs" werden Tabs farblich hervorgehoben. Hierbei wird die Tabgrenze dunkler dargestellt.

Mit "Color Spacs at end of line" werden Leerzeichen, in denen sich nicht der Cursor befindet, am Ende der Zeile rot markiert.

In der Konfigurationsdatei: ~/.config/chr kann mit der Option "formatting_characters=true", "color_tabs=true", "color_space_end=true" das Verhalten beeinflusst werden.

.SH Wrap long lines
Hier werden Zeilen, die über den Editorrand hinaus gezeichnet werden, abgeschnitten oder umgebrochen. Es kann an der Wortgrenze oder am Zeilenende hart umgebrochen werden. Diese Verhalten kann über die Option "wrap_lines=true" in der ~/.config/chr Datei beeinflusst werden.

Zudem kann mit der Option: "Display Right Margin at Column" ein numerischer Wert angegeben werden, ab dem die Hintergrundfarbe dunkel gefärbt wird. Dieser Wert lest sich auch mit der Konfigurationsoption: "right_margin_hint=80" in der ~/.config/chr einstellen.

.SH Following standard input
Wenn an den Editor mittels Standard-Eingabe Daten übergeben werden, kann mit dem Following-Mode immer an das aktuelle Ende der Datei gesprungen werden.

.SH Stop Input Pipe
Der Standard-Eingabedatei-Deskriptor wird geschlossen.

.SH Highlight Brackets
Es kann jeweils die folgende öffnende und schließende Klammer hervorgehoben werden, wenn der Cursor darüber fährt. Mit der Option "highlight_bracket=true" kann dieses Verhalten in der ~/.config/chr beeinflusst werden.
  [{(<>)}]

.SH Syntax Highlighting
Wenn zur Compilezeit die Option: "-Dsyntax_highlighting=true" gesetzt wurde, steht das Syntax Highlighting generell zur Verfügung. Die Sprache wird beim Öffnen einer Datei automatisch erkannt und in der Statusbar angezeigt. Bei Bedarf kann diese aber auch über das Syntax Highlighting Dialog ein uns aus bzw. angepasst werden.

Über die command line kann "--syntax-highlighting-theme" kann der theme angepasst werden. Der Editor bringt bereits die themes "chr-blugbg" und "chr-blackbg" mit. Bei Bedarf kann ein theme der von "kate-syntax-highlighter --list-themes" mitgebracht wird, benutzt werden.

Über die command line kann mittels "--disable-syntax=true" das Syntax Highlighting beim Starten des Editors ausgeschaltet werden.

.SH Theam
Es öffnet den Theam-Dialog zum auswählen eines Theme. Es steht der "Classic" (Blau) oder der "Dark" (schwarz weiß) Theme zur Verfügung. Mit der Option "theme=classic" oder "theme=dark", kann dies in der ~/.config/chr eingestellt werden.

.SH Window

.SH Next / Previous
Wechselt das aktive Fenster, mit Shift in umgekehrter Reihenfolge. (Siehe F6)

.SH Tile Vertically / Horizontally / Fullscreen
Zeigt mehre Fenster in den Positionen vertikal / horizontal / Vollbild an.

.SH CUSOM CONFIG
Hier werden Punkte aufgeführt, die ausschließlich in der ~/.config/chr beeinflusst werden können.

.SH Theme
Mit der Option "theme" kann der default hintergrund eingestellt werden. Zur auswahl stehen derzeit "classic" und "dark".

.SH Default config
Es gibt eine Default Config (~/.config/chr) in der folgenden Optionen gesetzt werden können.
  color_space_end=true
  color_tabs=true
  formatting_characters=true
  tab=false
  tabsize=8
  theme=classic
  wrap_lines=true
  right_margin_hint=80
  syntax_highlighter_themes="chr-bluebg"
  disable_syntax=false


.SH DESCRIPTION
Der chr Konsoleneditor ist angelehnt an den in Turbo Pascal geschriebenen Editor Tubo Vison aus dem Jahr 1997. Die Tastenkombinationen sollen denen von Gedit ähneln, um den Umstieg von Desktop- zu Konsoleneditor zu vereinfachen.

.SH BUGS
Alle Fehler in dieser Software können über den Bugtracker auf https://github.com/istoph/editor verwaltet werden.

.SH AUTHOR
Christoph Hüffelmann <chr@istoph.de>
Martin Hostettler <textshell@uchuujin.de>
